## 0. Import Libraries

In [151]:
import climextremes
import numpy as np
import pandas as pd

## 1. Open Data

In [5]:
dt = climextremes.Fort

In [6]:
dt

obs   tobs  month   day    year  Prec
1          1.0    1.0    1.0   1.0  1900.0   0.0
2          2.0    2.0    1.0   2.0  1900.0   0.0
3          3.0    3.0    1.0   3.0  1900.0   0.0
4          4.0    4.0    1.0   4.0  1900.0   0.0
5          5.0    5.0    1.0   5.0  1900.0   0.0
...        ...    ...    ...   ...     ...   ...
36520  36520.0  361.0   12.0  27.0  1999.0   0.0
36521  36521.0  362.0   12.0  28.0  1999.0   0.0
36522  36522.0  363.0   12.0  29.0  1999.0   0.0
36523  36523.0  364.0   12.0  30.0  1999.0   0.0
36524  36524.0  365.0   12.0  31.0  1999.0   0.0

[36524 rows x 6 columns]

In [7]:
dt['Prec'].describe()

count    36524.000000
mean         0.041814
std          0.166767
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          4.630000
Name: Prec, dtype: float64

## 3. Basic Explanations

**single block:** for Block Maximum approach think single block as a *one-year* (since there are yearly extreme values and a single block corresponds to each of these years). The definition for POT approaches can differ (i.e., monthly instead of yearly).

**The return probability** is the probability of exceeding the return value in a single block.

**The return period** is the average number of blocks expected to occur before the return value is exceeded and is equal to the inverse of **the probability of exceeding** the return value in a single block

**The return value** is the value for which the expected number of blocks until an event that exceeds that value is equal to the **return period**

**asymptotic distribution:** an asymptotic distribution exists if the probability distribution of Zi converges to a probability distribution (the asymptotic distribution) as i increases: see convergence in distribution. Read asymptotics as “what happens to the thing I’m estimating as my sample gets big? Approaching to the true distribution

In simple terms, any statistic can be a **point estimate**. A statistic is an estimator of some parameter in a population. For example:

- The sample standard deviation (s) is a *point estimate* of the population standard deviation (σ).
- The sample mean (̄x) is a *point estimate* of the population mean, μ.
- The sample variance (s2) is a *point estimate* of the population variance (σ2).

In more formal terms, the estimate occurs as a result of point estimation applied to a set of sample data. Points are single values, in comparison to **interval estimates**, which are a range of values. For example, a confidence interval is one example of an interval estimate.

**The delta method** is a general method for deriving the variance of a function of asymptotically normal random variables with known variance

There are a number of ways to compute the standard errors for the margins of a regression. It might be possible to derive a probability density function for the margin itself, but that’s perhaps a huge pain and might not even exist. It is also possible to use simulation or **bootstrapping** to create **standard errors** for the margin.

Why we use **log-return-periods(probability)**:
- log-normality
- approximate raw-log equality
- time-additivity
- mathematical ease
- numerical stability <br>

ref: [ref1](https://quantivity.wordpress.com/2011/02/21/why-log-returns/),
[ref2](https://gregorygundersen.com/blog/2022/02/06/log-returns/)

According to this definition, any variable that is measurable and considered to have a statistical relationship with the dependent variable would qualify as a potential **covariate**. A **covariate** is thus a possible predictive or explanatory variable of the dependent variable.

**The binomial distribution** is the discrete probability distribution that gives only two possible results in an experiment, either success or failure

**A risk ratio (RR)**, also called **relative risk**, compares the risk of a health event (disease, injury, risk factor, or death) among one group with the risk among another group. It does so by dividing the risk (incidence proportion, attack rate) in group 1 by the risk (incidence proportion, attack rate) in group 2

For our work: it is for counts of events relative to possible number of events (binomial). **The risk ratio** is the ratio of the probability of an event under the model fit to the first dataset to the probability under the model fit to the second dataset

**Maximum likelihood estimation (MLE)** is a method that determines values for the parameters of a model. The parameter values are found such that they maximise the likelihood that the process described by the model produced the data that were actually observed.

There is a technique that can help us find maxima (and minima) of functions. It’s called **differentiation**. All we have to do is find the **derivative** of the function, set the derivative function to zero and then rearrange the equation to make the parameter of interest the subject of the equation. And voilà, we’ll have our **MLE** values for our parameters.

Ref: [ref](https://towardsdatascience.com/probability-concepts-explained-maximum-likelihood-estimation-c7b4342fdbb1)

**MLE** is **asymtoptically** efficient: in the limit, a maximum likelihood estimator achieves minimum possible variance

**Bootstrapping** is a statistical procedure that resamples a single dataset to create many simulated samples. This process allows you to calculate **standard errors**, construct **confidence intervals**, and perform hypothesis testing for numerous types of sample statistics. **Bootstrap** methods are alternative approaches to traditional hypothesis testing and are notable for being easier to understand and valid for more conditions.

Ref: [ref](https://statisticsbyjim.com/hypothesis-testing/bootstrapping/)

In statistics, **the likelihood-ratio test** assesses the goodness of fit of two competing statistical models based on the ratio of their likelihoods, specifically one found by maximization over the entire parameter space and another found after imposing some constraint.

**A confidence interval**, in statistics, refers to the probability that a population parameter will fall between a set of values for a certain proportion of times. Analysts often use confidence intervals than contain either 95% or 99% of expected observations. Thus, if a point estimate is generated from a statistical model of 10.00 with a 95% confidence interval of 9.50 - 10.50, it can be inferred that there is a 95% probability that the true value falls within that range.

They are also used in **hypothesis testing** and regression analysis.
Statisticians often use **p-values** in conjunction with **confidence intervals** to gauge **statistical significance**.

Note that if only one endpoint of the resulting interval is used, for example the lower bound, then the effective confidence level increases by half of one minus confidence level. For example, a two-sided 0.90 **confidence interval** corresponds to a one-sided 0.95 confidence interval.

***NOW READ: [DOCUMENTATION](https://cran.r-project.org/web/packages/climextRemes/climextRemes.pdf)***

## 4. Tools

### 3.1 calc_logReturnPeriod_fevd

In [11]:
help(climextremes.calc_logReturnPeriod_fevd)

Help on function calc_logReturnPeriod_fevd:

calc_logReturnPeriod_fevd(fit=None, returnValue=None, covariates=None, upper=False)
    Calculates log return period and standard error given return value(s) of interest 
    
    **description**
    
     Calculates log return period given return value(s) of interest, using model fit from  extRemes::fevd . Standard error is obtained via the delta method. The return period is the average number of blocks expected to occur before the return value is exceeded and is equal to the inverse of the probability of exceeding the return value in a single block. For non-stationary models (those that include covariates for the location, scale, and/or shape parameters, log return periods and standard errors are returned for as many sets of covariates as provided.
    
    **arguments**
    
     fit: fitted object from extRemes fevd
    
     returnValue: value(s) for which return period is desired
    
     covariates: matrix of covariate values, each r

### 3.2 calc_logReturnProbDiff_fevd

In [12]:
help(climextremes.calc_logReturnProbDiff_fevd)

Help on function calc_logReturnProbDiff_fevd:

calc_logReturnProbDiff_fevd(fit=None, returnValue=None, covariates1=None, covariates2=None, getSE=True, scaling=1.0, upper=False)
    Calculates log return probability difference for two sets of covariates and standard error of difference given return value(s) of interest 
    
    **description**
    
     Calculates difference in log return probabilities for two sets of covariates given return value(s) of interest, using model fit from  extRemes::fevd . Standard error is obtained via the delta method. The return probability is the probability of exceeding the return value in a single block. Differences and standard errors are returned for as many contrasts between covariate sets as provided.
    
    **arguments**
    
     fit: fitted object from extRemes fevd
    
     returnValue: value(s) for which the log return probability difference is desired
    
     covariates1: matrix of covariate values, each row a set of covariates for whic

### 3.3 calc_logReturnProb_fevd

In [14]:
help(climextremes.calc_logReturnProb_fevd)

Help on function calc_logReturnProb_fevd:

calc_logReturnProb_fevd(fit=None, returnValue=None, covariates=None, getSE=True, scaling=1.0, upper=False)
    Calculates log return probability and standard error given return value(s) of interest 
    
    **description**
    
     Calculates log return probability given return value(s) of interest, using model fit from  extRemes::fevd . Standard error is obtained via the delta method. The return probability is the probability of exceeding the return value in a single block. For non-stationary models (those that include covariates for the location, scale, and/or shape parameters, log probabilities and standard errors are returned for as many sets of covariates as provided.
    
    **arguments**
    
     fit: fitted object from extRemes fevd
    
     returnValue: value(s) for which log return probability is desired
    
     covariates: matrix of covariate values, each row a set of covariates for which the return probability is desired
   

### 3.4 calc_returnValueDiff_fevd

In [15]:
help(climextremes.calc_returnValueDiff_fevd)

Help on function calc_returnValueDiff_fevd:

calc_returnValueDiff_fevd(fit=None, returnPeriod=None, covariates1=None, covariates2=None, getSE=True)
    Calculates return value difference for two sets of covariates and standard error of difference given return period(s) of interest 
    
    **description**
    
     Calculates difference in return values (also known as return levels) for two sets of covariates given return period(s) of interest, using model fit from  extRemes::fevd . Standard error is obtained via the delta method. The return value is the value for which the expected number of blocks until an event that exceeds that value is equal to the return period. Differences and standard errors are returned for as many contrasts between covariate sets as provided.
    
    **arguments**
    
     fit: fitted object from extRemes fevd
    
     returnPeriod: value(s) for which return value difference is desired
    
     covariates1: matrix of covariate values, each row a set of c

### 3.5 calc_returnValue_fevd

In [17]:
help(climextremes.calc_returnValue_fevd)

Help on function calc_returnValue_fevd:

calc_returnValue_fevd(fit=None, returnPeriod=None, covariates=None)
    Calculates return value and standard error given return period(s) of interest 
    
    **description**
    
     Calculates return value (also known as the return level) given return period(s) of interest, using model fit from  extRemes::fevd . Standard error is obtained via the delta method. The return value is the value for which the expected number of blocks until an event that exceeds that value is equal to the return period. For non-stationary models (those that include covariates for the location, scale, and/or shape parameters, return values and standard errors are returned for as many sets of covariates as provided.
    
    **arguments**
    
     fit: fitted object from extRemes fevd
    
     returnPeriod: value(s) for which return value is desired
    
     covariates: matrix of covariate values, each row a set of covariates for which the return value is desired

### 3.6 calc_riskRatio_binom

In [18]:
help(climextremes.calc_riskRatio_binom)

Help on function calc_riskRatio_binom:

calc_riskRatio_binom(y=None, n=None, ciLevel=0.9, ciType=None, bootSE=None, bootControl=None, lrtControl=None)
    Compute risk ratio and uncertainty based on binomial models for counts of events relative to possible number of events 
    
    **description**
    
     Compute risk ratio and uncertainty by fitting binomial models to counts of events relative to possible number of events. The risk ratio is the ratio of the probability of an event under the model fit to the first dataset to the probability under the model fit to the second dataset. Default standard errors are based on the usual MLE asymptotics using a delta-method-based approximation, but standard errors based on the nonparametric bootstrap and on a likelihood ratio procedure can also be computed.
    
    **arguments**
    
    y: numpy array of two values, the number of events in the two scenarios.
    
    n: numpy array of two values, the number of samples (possible occurrences

#### 3.6.1 Example

In [23]:
# risk ratio for 40/400 compared to 8/400 events
result = climextremes.calc_riskRatio_binom(np.array((40, 8)), 
                                           np.array((400, 400)),
                                           ciType = np.array(('lrt',
                                                              'boot_stud',
                                                              'koopman'))
                                          )

In [30]:
# log risk ratio between first and second events
result['logRiskRatio']

array([1.60943791])

In [34]:
# standard error of log risk ratio (point estimate) based on delta method
result['se_logRiskRatio']

array([0.38078866])

In [35]:
# raw risk ratio between first and second events
result['riskRatio']

array([5.])

In [36]:
# confidence interval of risk ratio based on likelihood ratio test
# between events
result['ci_riskRatio_lrt']

array([2.78391806, 9.86604856])

In [37]:
# confidence interval of risk ratio based on koopman method
# between events
result['ci_riskRatio_koopman']

array([2.70619164, 9.27887211])

In [39]:
# confidence interval of risk ratio based on students t bootstrap
# between events
result['ci_riskRatio_boot_stud']

array([ 2.57683507, 10.92551928])

In [40]:
# Koopman and LRT method can estimate lower confidence interval endpoint,
# even if estimated risk ratio is infinity
# risk ratio for 4/100 compared to 0/100 events
result = climextremes.calc_riskRatio_binom(np.array((4, 0)), 
                                           np.array((100, 100)),
                                           ciType = np.array(('lrt',
                                                              'koopman'))
                                          )

In [41]:
# confidence interval of risk ratio based on likelihood ratio test
# between events
result['ci_riskRatio_lrt']

array([2.51387752,        inf])

In [42]:
# confidence interval of risk ratio based on koopman method
# between events
result['ci_riskRatio_koopman']

array([1.50254114,        inf])

### 3.7 calc_riskRatio_gev

In [43]:
help(climextremes.calc_riskRatio_gev)

Help on function calc_riskRatio_gev:

calc_riskRatio_gev(returnValue=None, y1=None, y2=None, x1=None, x2=None, locationFun1=None, locationFun2=None, scaleFun1=None, scaleFun2=None, shapeFun1=None, shapeFun2=None, nReplicates1=1.0, nReplicates2=1.0, replicateIndex1=None, replicateIndex2=None, weights1=None, weights2=None, xNew1=None, xNew2=None, maxes=True, scaling1=1.0, scaling2=1.0, ciLevel=0.9, ciType=None, bootSE=None, bootControl=None, lrtControl=None, optimArgs=None, optimControl=None, initial1=None, initial2=None, logScale1=None, logScale2=None, getReturnCalcs=False, getParams=False, getFit=False)
    Compute risk ratio and uncertainty based on generalized extreme value model fit to block maxima or minima 
    
    **description**
    
     Compute risk ratio and uncertainty by fitting generalized extreme value model, designed specifically for climate data, to exceedance-only data, using the point process approach. The risk ratio is the ratio of the probability of exceedance of a

#### 3.7.1 Example

In [8]:
earlyPeriod = np.array((1900, 1930))
earlyYears = np.array(range(earlyPeriod[0], earlyPeriod[1]))

latePeriod = np.array((1970, 2000))
lateYears = np.array(range(latePeriod[0], latePeriod[1]))

dtMax = dt.groupby('year').max()[['Prec']]
dtMax.reset_index(inplace=True)

In [10]:
dt.head(4)

obs  tobs  month  day    year  Prec
1  1.0   1.0    1.0  1.0  1900.0   0.0
2  2.0   2.0    1.0  2.0  1900.0   0.0
3  3.0   3.0    1.0  3.0  1900.0   0.0
4  4.0   4.0    1.0  4.0  1900.0   0.0

In [12]:
dtMax.head(4)

year  Prec
0  1900.0  2.39
1  1901.0  2.32
2  1902.0  4.34
3  1903.0  0.85

In [16]:
y1 = dtMax.Prec[dtMax.year < earlyPeriod[1]]
y2 = dtMax.Prec[dtMax.year >= latePeriod[0]]

In [17]:
y1

0     2.39
1     2.32
2     4.34
3     0.85
4     3.02
5     1.74
6     1.70
7     1.21
8     1.93
9     1.68
10    1.48
11    1.16
12    1.32
13    1.32
14    1.44
15    1.83
16    2.23
17    0.96
18    2.98
19    0.97
20    1.16
21    1.46
22    0.84
23    2.30
24    1.38
25    1.70
26    1.17
27    1.15
28    1.32
29    1.25
Name: Prec, dtype: float64

In [36]:
# contrast late period with early period, assuming a nonstationary fit
# within each time period and finding RR based on midpoint of each period

result = climextremes.calc_riskRatio_gev(
    returnValue = 3,
    y1 = np.array(y1), y2 = np.array(y2),
    x1 = earlyYears, x2 = lateYears,
    locationFun1 = 1, locationFun2 = 1,
    xNew1 = int(earlyYears.mean()), xNew2 = int(lateYears.mean()),
    ciType = 'lrt'
        )

In [37]:
result

{'logRiskRatio': array([-0.74591629]),
 'se_logRiskRatio': array([0.76214254]),
 'riskRatio': array([0.4742995]),
 'ci_riskRatio_lrt_names': array(['0.05', '0.95'], dtype='<U4'),
 'ci_riskRatio_lrt': array([0.13618289, 1.5597101 ])}

### 3.8 calc_riskRatio_pot

In [38]:
help(climextremes.calc_riskRatio_pot)

Help on function calc_riskRatio_pot:

calc_riskRatio_pot(returnValue=None, y1=None, y2=None, x1=None, x2=None, threshold1=None, threshold2=None, locationFun1=None, locationFun2=None, scaleFun1=None, scaleFun2=None, shapeFun1=None, shapeFun2=None, nBlocks1=None, nBlocks2=None, blockIndex1=None, blockIndex2=None, firstBlock1=1.0, firstBlock2=1.0, index1=None, index2=None, nReplicates1=1.0, nReplicates2=1.0, replicateIndex1=None, replicateIndex2=None, weights1=None, weights2=None, proportionMissing1=None, proportionMissing2=None, xNew1=None, xNew2=None, declustering=None, upperTail=True, scaling1=1.0, scaling2=1.0, ciLevel=0.9, ciType=None, bootSE=None, bootControl=None, lrtControl=None, optimArgs=None, optimControl=None, initial1=None, initial2=None, logScale1=None, logScale2=None, getReturnCalcs=False, getParams=False, getFit=False)
    Compute risk ratio and uncertainty based on peaks-over-threshold models fit to exceedances over a threshold 
    
    **description**
    
     Compute 

#### 3.8.1 Example

In [125]:
threshold = 0.395
dtExc = dt[dt.Prec > threshold]

earlyPeriod = np.array((1900, 1930))
earlyYears = np.array(range(earlyPeriod[0], earlyPeriod[1]))

latePeriod = np.array((1970, 2000))
lateYears = np.array(range(latePeriod[0], latePeriod[1]))
    
y1 = dtExc.Prec[dtExc.year < earlyPeriod[1]]
y2 = dtExc.Prec[dtExc.year >= latePeriod[0]]

block1 = dtExc.year[dtExc.year < earlyPeriod[1]]
block2 = dtExc.year[dtExc.year >= latePeriod[0]]

In [126]:
dtExc.head(4)

obs  tobs  month   day    year  Prec
86  86.0  86.0    3.0  27.0  1900.0  0.57
94  94.0  94.0    4.0   4.0  1900.0  1.52
95  95.0  95.0    4.0   5.0  1900.0  0.49
99  99.0  99.0    4.0   9.0  1900.0  0.91

In [131]:
y2

25644    0.51
25656    0.92
25675    0.48
25729    2.40
25730    0.56
         ... 
36375    1.63
36403    0.94
36430    0.76
36448    0.63
36485    0.59
Name: Prec, Length: 348, dtype: float64

In [130]:
block2

25644    1970.0
25656    1970.0
25675    1970.0
25729    1970.0
25730    1970.0
          ...  
36375    1999.0
36403    1999.0
36430    1999.0
36448    1999.0
36485    1999.0
Name: year, Length: 348, dtype: float64

In [124]:
len(np.array(block1))

333

In [149]:
# contrast late period with early period, assuming a nonstationary fit
# within each time period and finding RR based on midpoint of each period
result = climextremes.calc_riskRatio_pot(
    returnValue = 3,
    
    y1 = np.array(y1),
    y2 = np.array(y2),
    
    x1 = earlyYears,
    x2 = lateYears,
    
    threshold1 = threshold, 
    threshold2 = threshold,
    
    locationFun1 = 1, 
    locationFun2 = 1,
    
    xNew1 = int(earlyYears.mean()), 
    xNew2 = int(lateYears.mean()),
    
    blockIndex1 = np.array(block1),
    blockIndex2 = np.array(block2),
    
    firstBlock1 = float(earlyYears[0]), # py2r sorunu buradan dolayı
    firstBlock2 = float(lateYears[0]), # float kullanmak gerek
    
    ciType = 'lrt')

In [150]:
result

{'logRiskRatio': array([-0.68988299]),
 'se_logRiskRatio': array([0.62212738]),
 'riskRatio': array([0.50163476]),
 'ci_riskRatio_lrt_names': array(['0.05', '0.95'], dtype='<U4'),
 'ci_riskRatio_lrt': array([0.18263271, 1.33406702])}